import AgentNode, { SubAgentNode } from './agentNode'

import {
  ToolNode,
  InputNode,
  OutputNode,
  gmailNode,
  driveNode,
  notionNode,
  slackNode,
  vectordbNode,
  embeddingModelNode,
  calendarNode,
  discordNode,
  scheduleTriggerNode,
  httpNode,
  chatTriggerNode,
  retrieverNode,
  sendDataNode,
  googleSheetNode,
  ifNode,
  switchNode,
  loopNode,
  delayNode,
  emailNode,
  telegramNode,
  webhookNode,
  dataFormatterNode,
  codeNode,
  errorHandlerNode,
  whatsAppNode,
  csvLoaderNode,
  pdfConverterNode
} from './standard-nodes'

import modelNode from './modelNode'

export const nodeTypes = {
  agent: AgentNode,
  subAgent: SubAgentNode,
  modelNode: modelNode,
  tool: ToolNode,
  inputNode: InputNode,
  outputNode: OutputNode,
  gmailNode: gmailNode,
  driveNode: driveNode,
  notionNode: notionNode,
  slackNode: slackNode,
  vectordbNode: vectordbNode,
  embeddingModelNode: embeddingModelNode,
  calendarNode: calendarNode,
  discordNode: discordNode,
  scheduleTriggerNode: scheduleTriggerNode,
  httpNode: httpNode,
  chatTriggerNode: chatTriggerNode,
  retrieverNode: retrieverNode,
  sendDataNode: sendDataNode,
  groqNode: modelNode,
  mongoDBNode: modelNode,
  googleSheetNode: googleSheetNode,
  ifNode: ifNode,
  switchNode: switchNode,
  loopNode: loopNode,
  delayNode: delayNode,
  emailNode: emailNode,
  telegramNode: telegramNode,
  webhookNode: webhookNode,
  dataFormatterNode: dataFormatterNode,
  codeNode: codeNode,
  errorHandlerNode: errorHandlerNode,
  whatsAppNode: whatsAppNode,
  csvLoaderNode: csvLoaderNode,
  pdfConverterNode: pdfConverterNode,
}